const $=s=>document.querySelector(s),feed=$('#feed');let rec=null,listening=false;const synth=window.speechSynthesis;
function esc(s){return String(s).replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]))}function add(w,m){const p=document.createElement('p');p.innerHTML=`<b>${w}:</b> ${esc(m)}`;feed.appendChild(p);feed.scrollTop=feed.scrollHeight}
function speak(t){add('NOVA',t);if(!synth)return;synth.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='hi-IN';u.pitch=+$('#pitch').value;u.rate=+$('#rate').value;const v=synth.getVoices();u.voice=v.find(x=>/hi[-_]IN/i.test(x.lang)&&/male|deep|man|ravi|amit|rahul/i.test(x.name))||v.find(x=>/hi[-_]IN/i.test(x.lang))||v.find(x=>/^en/i.test(x.lang))||v[0];synth.speak(u)}
function local(q){const x=q.toLowerCase();if(/समय|time|clock|कितने बजे/.test(x))return 'अभी '+new Intl.DateTimeFormat('hi-IN',{timeStyle:'medium',timeZone:'Asia/Kolkata'}).format(new Date())+' है।';if(/तारीख|date|today|आज की तारीख/.test(x))return 'आज '+new Intl.DateTimeFormat('hi-IN',{dateStyle:'full',timeZone:'Asia/Kolkata'}).format(new Date())+' है।';if(/जोक|joke|मजाक|हंसाओ/.test(x))return 'मेरी processing इतनी तेज है कि Wi-Fi भी मुझसे कहता है—भाई थोड़ा धीरे! 😄';if(/मोटिवेट|motivat|हिम्मत/.test(x))return 'एक छोटा कदम अभी उठाओ। बाकी रास्ता हम साथ तय करेंगे।';if(/नमस्ते|hello|hi|hey/.test(x))return 'नमस्ते Mohit! NOVA online है।';if(/तुम कौन|who are you/.test(x))return 'मैं NOVA हूँ—तुम्हारा futuristic personal AI assistant.';return null}
async function ai(q){try{const history=[...feed.querySelectorAll('p')].slice(-12).map(p=>({role:/^YOU:/.test(p.textContent)?'user':'assistant',content:p.textContent.replace(/^[^:]+:\s*/, '')}));const r=await fetch(NOVA_CONFIG.BACKEND_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,history,useWeb:/latest|today|news|current|आज|ताज़ा|ताजा/.test(q.toLowerCase())})});if(!r.ok)throw new Error('backend');const d=await r.json();return d.reply||d.output_text||null}catch(e){return null}}
async function ask(q){q=q.trim();if(!q)return;add('YOU',q);$('#thinking').textContent='THINKING…';$('#core').textContent='PROCESSING';let a=local(q);if(!a)a=await ai(q);if(!a)a='अभी AI backend से जवाब नहीं मिला। Vercel में OPENAI_API_KEY, OPENAI_MODEL और ALLOWED_ORIGIN की settings जाँचें।';$('#thinking').textContent='READY';$('#core').textContent='READY';speak(a)}
$('#ask').onclick=()=>{const q=$('#q').value;$('#q').value='';ask(q)};$('#q').onkeydown=e=>{if(e.key==='Enter')$('#ask').click()};$('#clear').onclick=()=>feed.innerHTML='';$('#test').onclick=()=>speak('नमस्ते Mohit. मैं NOVA हूँ। Deep futuristic voice mode में online हूँ।');
function start(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return speak('इस browser में voice recognition उपलब्ध नहीं है।');rec=new R();rec.lang='hi-IN';rec.continuous=true;rec.interimResults=false;rec.onstart=()=>{listening=true;document.body.classList.add('listening');$('#listen').textContent='LISTENING';$('#voiceState').textContent='ACTIVE'};rec.onend=()=>{if(listening)try{rec.start()}catch(e){}};rec.onerror=()=>{};rec.onresult=e=>{const t=e.results[e.results.length-1][0].transcript;if(/nova|नोवा/i.test(t)){const q=t.replace(/nova|नोवा/ig,'').trim();ask(q||'नमस्ते')}};try{rec.start()}catch(e){}}
function stop(){listening=false;document.body.classList.remove('listening');$('#listen').textContent='STANDBY';$('#voiceState').textContent='STANDBY';try{rec?.stop()}catch(e){}}$('#voice').onclick=()=>listening?stop():start();
const themes={cyan:['#54e8ff','#9b7bff'],purple:['#b48cff','#ff6adf'],red:['#ff5577','#ff9b54'],gold:['#ffd166','#ff9f1c'],ice:['#8fe8ff','#b9c7ff'],matrix:['#56ff8c','#00d9a5'],midnight:['#8ba7ff','#5864ff'],neon:['#00ffd5','#ff36c8']};document.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{const v=themes[b.dataset.t];document.documentElement.style.setProperty('--c',v[0]);document.documentElement.style.setProperty('--c2',v[1]);localStorage.NOVA_THEME=b.dataset.t});if(localStorage.NOVA_THEME&&themes[localStorage.NOVA_THEME]){const v=themes[localStorage.NOVA_THEME];document.documentElement.style.setProperty('--c',v[0]);document.documentElement.style.setProperty('--c2',v[1])}
document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>ask(b.dataset.q));document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{const a=b.dataset.a;if(window.Android){if(['whatsapp','youtube','instagram','chrome','camera'].includes(a))Android.openApp(a);else Android.openSettings(a);$('#androidState').textContent='ANDROID'}else speak('यह phone control NOVA Android app में उपलब्ध है।')});
$('#full').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()};$('#themeBtn').onclick=()=>document.querySelector('.themes')?.scrollIntoView({behavior:'smooth'});
setInterval(()=>{$('#clock').textContent=new Intl.DateTimeFormat('en-IN',{timeStyle:'medium',hour12:false,timeZone:'Asia/Kolkata'}).format(new Date());$('#date').textContent=new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeZone:'Asia/Kolkata'}).format(new Date())},500);
async function weather(){try{const r=await fetch('https://api.open-meteo.com/v1/forecast?latitude=26.9124&longitude=75.7873&current=temperature_2m,weather_code&timezone=Asia%2FKolkata');const d=await r.json();$('#weather').textContent=Math.round(d.current.temperature_2m)+'°C'}catch(e){$('#weather').textContent='READY'}}weather();
