const $=s=>document.querySelector(s),feed=$('#feed');let token=sessionStorage.getItem('NOVA_AUTH_TOKEN')||'',rec=null,listening=false,speech=speechSynthesis;
function add(w,m){const p=document.createElement('p');p.innerHTML=`<b>${w}:</b> ${String(m).replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]))}`;feed.appendChild(p);feed.scrollTop=feed.scrollHeight}
function voice(t){add('NOVA',t);if(!speech)return;speech.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='hi-IN';u.pitch=+$('#pitch').value;u.rate=+$('#rate').value;const vs=speech.getVoices();u.voice=vs.find(v=>/hi[-_]IN/i.test(v.lang)&&/male|deep|man|ravi|amit|rahul/i.test(v.name))||vs.find(v=>/hi[-_]IN/i.test(v.lang))||vs[0];speech.speak(u)}
async function auth(){const pw=$('#password').value;if(!pw)return $('#loginMsg').textContent='Password डालो।';$('#loginMsg').textContent='AUTHENTICATING…';try{const r=await fetch(NOVA_CONFIG.AUTH_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:pw})});const d=await r.json();if(!r.ok)throw 0;token=d.token;sessionStorage.setItem('NOVA_AUTH_TOKEN',token);$('#loginGate').style.display='none';$('#app').classList.remove('locked');voice('Private access granted. नमस्ते Mohit, NOVA online है।')}catch(e){$('#loginMsg').textContent='Password गलत है या backend उपलब्ध नहीं है।'}}
async function ai(q){if(!token)return null;try{const hist=[...feed.querySelectorAll('p')].slice(-10).map(p=>({role:/^YOU:/.test(p.textContent)?'user':'assistant',content:p.textContent.replace(/^[^:]+:\s*/,'')}));const r=await fetch(NOVA_CONFIG.BACKEND_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({message:q,history:hist,useWeb:/latest|today|news|current|आज|ताज़ा|ताजा/.test(q.toLowerCase())})});if(r.status===401){logout();return null}if(!r.ok)return null;return (await r.json()).reply||null}catch(e){return null}}
function local(q){const x=q.toLowerCase();if(/समय|time|clock|कितने बजे/.test(x))return 'अभी '+new Intl.DateTimeFormat('hi-IN',{timeStyle:'medium',timeZone:'Asia/Kolkata'}).format(new Date())+' है।';if(/तारीख|date|today/.test(x))return 'आज '+new Intl.DateTimeFormat('hi-IN',{dateStyle:'full',timeZone:'Asia/Kolkata'}).format(new Date())+' है।';if(/जोक|joke|मजाक|हंसाओ/.test(x))return 'मेरी processing इतनी तेज है कि Wi-Fi भी मुझसे कहता है—भाई थोड़ा धीरे! 😄';if(/मोटिवेट|motivat|हिम्मत/.test(x))return 'एक छोटा कदम अभी उठाओ। बाकी रास्ता हम साथ तय करेंगे।';if(/नमस्ते|hello|hi|hey/.test(x))return 'नमस्ते Mohit! NOVA online है।';return null}
async function ask(q){q=q.trim();if(!q)return;add('YOU',q);$('#thinking').textContent='THINKING…';$('#core').textContent='PROCESSING';let a=local(q);if(!a)a=await ai(q);if(!a)a='माफ़ करना Mohit, AI backend से जवाब नहीं मिला। Vercel में OPENAI_API_KEY, OPENAI_MODEL, ALLOWED_ORIGIN और NOVA_ACCESS_PASSWORD check करो।';$('#thinking').textContent='READY';$('#core').textContent='READY';voice(a)}
$('#ask').onclick=()=>{const q=$('#q').value;$('#q').value='';ask(q)};$('#q').onkeydown=e=>{if(e.key==='Enter'){$('#ask').click()}};$('#unlock').onclick=auth;$('#password').onkeydown=e=>{if(e.key==='Enter')auth()};$('#test').onclick=()=>voice('नमस्ते Mohit. मैं NOVA हूँ। Deep voice mode में तुम्हारा personal AI system online है।');
function logout(){token='';sessionStorage.removeItem('NOVA_AUTH_TOKEN');$('#app').classList.add('locked');$('#loginGate').style.display='grid';if(listening)stop()};$('#logout').onclick=logout;
function start(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return voice('इस browser में voice recognition उपलब्ध नहीं है।');rec=new R();rec.lang='hi-IN';rec.continuous=true;rec.interimResults=false;rec.onstart=()=>{listening=true;document.body.classList.add('listening');$('#listen').textContent='LISTENING'};rec.onend=()=>{if(listening)try{rec.start()}catch(e){}};rec.onresult=e=>{const t=e.results[e.results.length-1][0].transcript;if(/nova|नोवा/i.test(t))ask(t.replace(/nova|नोवा/ig,'').trim()||'नमस्ते')};rec.start()}function stop(){listening=false;document.body.classList.remove('listening');$('#listen').textContent='STANDBY';rec?.stop()}$('#voice').onclick=()=>listening?stop():start();
const themes={cyan:['#54e8ff','#9b7bff'],purple:['#b48cff','#ff6adf'],red:['#ff5577','#ff9b54'],gold:['#ffd166','#ff9f1c'],ice:['#8fe8ff','#b9c7ff'],matrix:['#56ff8c','#00d9a5']};document.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{const v=themes[b.dataset.t];document.documentElement.style.setProperty('--c',v[0]);document.documentElement.style.setProperty('--c2',v[1])});document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>window.Android?((['whatsapp','youtube','instagram','chrome','camera'].includes(b.dataset.a))?Android.openApp(b.dataset.a):Android.openSettings(b.dataset.a)):voice('इस action के लिए NOVA Android app इस्तेमाल करें।'));
setInterval(()=>{$('#clock').textContent=new Intl.DateTimeFormat('en-IN',{timeStyle:'medium',hour12:false,timeZone:'Asia/Kolkata'}).format(new Date());$('#date').textContent=new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeZone:'Asia/Kolkata'}).format(new Date())},500);if(token){$('#loginGate').style.display='none';$('#app').classList.remove('locked')}
